#ifndef GAME_ENGINE_SETTINGS
#define GAME_ENGINE_SETTINGS

const int CRITICAL_FPS_RATE = 1;

enum PAUSE_MODE {
	NO_PAUSE = 0,
	PAUSE = 1,
	ONE_FRAME = 2,
};

const double OBJECTS_BUFFER_REFRESH_COEF = 0.2;

#define PHYSICS_TIME_STEP 0.001

#endif // GAME_ENGINE_SETTINGS